# Generated by Django 3.1.1 on 2021-08-15 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.CharField(default='', max_length=30, unique=True)),
                ('video', models.FileField(upload_to='video/')),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_field', models.DateField(auto_now_add=True)),
                ('date_time_field', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.video')),
            ],
        ),
    ]
